### ISSUE TITLE
Is it just me or does this not compile?

### ISSUE THREAD

**Issue by stevemesser** [briansain/Akka.Skeleton#3]

**Comment by briansain** [comment]
I just pulled this down to a fresh folder and was able to compile it. What IDE are you using, and which project did you try to build?

**Comment by stevemesser** [comment]
Visual Studio 2022

**Comment by stevemesser** [comment]
Fails to restore nuget packages

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1301	The local source 'F:\New folder' doesn't exist.	Akka.Skeleton	F:\_OpenSource\Akka.Skeleton\Akka.Skeleton\Akka.Skeleton.csproj	1

**Comment by stevemesser** [comment]
Seems I was a couple of updates behind. One of the addressed issues was NuGet handling. Works now.
